In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("C:/Users/Dell/Downloads/covid-19 dataset/data.csv")

In [4]:
data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [5]:
data.tail()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
162602,ZWE,Africa,Zimbabwe,2022-02-13,231381.0,82.0,139.857,5374.0,0.0,1.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
162603,ZWE,Africa,Zimbabwe,2022-02-14,231603.0,222.0,171.571,5374.0,0.0,1.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
162604,ZWE,Africa,Zimbabwe,2022-02-15,231603.0,0.0,142.857,5374.0,0.0,1.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
162605,ZWE,Africa,Zimbabwe,2022-02-16,232213.0,610.0,210.429,5379.0,5.0,1.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
162606,ZWE,Africa,Zimbabwe,2022-02-17,232598.0,385.0,222.571,5381.0,2.0,1.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [6]:
data.columns.unique()

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [8]:
data.isnull().sum()

iso_code                                        0
continent                                    9748
location                                        0
date                                            0
total_cases                                  2965
                                            ...
human_development_index                     29408
excess_mortality_cumulative_absolute       157087
excess_mortality_cumulative                157087
excess_mortality                           157075
excess_mortality_cumulative_per_million    157087
Length: 67, dtype: int64

In [10]:
data.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,1.596420e+05,1.596160e+05,1.584650e+05,1.419460e+05,142122.000000,141992.000000,158900.000000,158874.000000,157728.000000,141217.000000,...,103684.000000,102261.000000,67022.000000,120914.000000,151784.000000,133199.000000,5.520000e+03,5520.000000,5532.000000,5520.000000
mean,2.409186e+06,1.113121e+04,1.104852e+04,5.628826e+04,171.251537,170.396181,27488.320256,157.515189,155.410939,494.500067,...,10.630869,32.771251,50.783030,3.028169,73.577365,0.725641,3.685615e+04,9.213859,15.987232,924.226535
std,1.451968e+07,8.234078e+04,7.994272e+04,2.951279e+05,833.832188,811.973637,47095.438489,655.527673,502.408392,766.595694,...,10.560549,13.519607,31.808301,2.450961,7.493322,0.149988,1.027585e+05,16.497870,30.375823,1373.111371
min,1.000000e+00,-7.434700e+04,-6.223000e+03,1.000000e+00,-1918.000000,-232.143000,0.001000,-13876.282000,-1936.106000,0.000000,...,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000,-3.772610e+04,-28.450000,-95.920000,-1826.595723
25%,1.876000e+03,1.000000e+00,6.714000e+00,7.600000e+01,0.000000,0.143000,590.182250,0.041000,1.582000,17.758000,...,1.900000,21.600000,19.351000,1.300000,69.500000,0.602000,-8.922500e+01,-0.890000,-0.830000,-37.027419
50%,2.474250e+04,7.800000e+01,1.040000e+02,7.540000e+02,2.000000,2.429000,4510.864500,11.203000,18.046500,120.273000,...,6.300000,31.400000,49.839000,2.400000,75.050000,0.743000,3.217500e+03,5.755000,7.130000,436.789598
75%,2.838548e+05,1.037000e+03,1.103286e+03,7.093000e+03,19.000000,20.571000,35395.976000,98.096000,115.349000,685.162000,...,19.300000,41.300000,83.241000,4.000000,78.930000,0.845000,2.413720e+04,14.300000,22.947500,1578.960127
max,4.196935e+08,4.234868e+06,3.438717e+06,5.863136e+06,18057.000000,14705.714000,623223.860000,51427.491000,16052.608000,6264.019000,...,44.000000,78.100000,100.000000,13.800000,86.750000,0.957000,1.080748e+06,111.010000,374.600000,8626.892312